/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[notFound]': RouteRecordInfo<'/[notFound]', '/:notFound', { notFound: ParamValue<true> }, { notFound: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/contact/': RouteRecordInfo<'/contact/', '/contact', Record<never, never>, Record<never, never>>,
    '/services/': RouteRecordInfo<'/services/', '/services', Record<never, never>, Record<never, never>>,
    '/services/brand-strategy/': RouteRecordInfo<'/services/brand-strategy/', '/services/brand-strategy', Record<never, never>, Record<never, never>>,
    '/services/design-collaterals/': RouteRecordInfo<'/services/design-collaterals/', '/services/design-collaterals', Record<never, never>, Record<never, never>>,
    '/services/digital-marketing/': RouteRecordInfo<'/services/digital-marketing/', '/services/digital-marketing', Record<never, never>, Record<never, never>>,
    '/services/naming-copy/': RouteRecordInfo<'/services/naming-copy/', '/services/naming-copy', Record<never, never>, Record<never, never>>,
    '/services/packaging-design/': RouteRecordInfo<'/services/packaging-design/', '/services/packaging-design', Record<never, never>, Record<never, never>>,
    '/services/performance-marketing/': RouteRecordInfo<'/services/performance-marketing/', '/services/performance-marketing', Record<never, never>, Record<never, never>>,
    '/services/visual-identity/': RouteRecordInfo<'/services/visual-identity/', '/services/visual-identity', Record<never, never>, Record<never, never>>,
    '/services/website-design/': RouteRecordInfo<'/services/website-design/', '/services/website-design', Record<never, never>, Record<never, never>>,
    '/thank-you/': RouteRecordInfo<'/thank-you/', '/thank-you', Record<never, never>, Record<never, never>>,
    '/work/': RouteRecordInfo<'/work/', '/work', Record<never, never>, Record<never, never>>,
    '/work/[slug]': RouteRecordInfo<'/work/[slug]', '/work/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
  }
}
