/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[notFound]': RouteRecordInfo<'/[notFound]', '/:notFound', { notFound: ParamValue<true> }, { notFound: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/brand-strategy/': RouteRecordInfo<'/brand-strategy/', '/brand-strategy', Record<never, never>, Record<never, never>>,
    '/contact/': RouteRecordInfo<'/contact/', '/contact', Record<never, never>, Record<never, never>>,
    '/design-collaterals/': RouteRecordInfo<'/design-collaterals/', '/design-collaterals', Record<never, never>, Record<never, never>>,
    '/digital-marketing/': RouteRecordInfo<'/digital-marketing/', '/digital-marketing', Record<never, never>, Record<never, never>>,
    '/naming-copy/': RouteRecordInfo<'/naming-copy/', '/naming-copy', Record<never, never>, Record<never, never>>,
    '/packaging-design/': RouteRecordInfo<'/packaging-design/', '/packaging-design', Record<never, never>, Record<never, never>>,
    '/performance-marketing/': RouteRecordInfo<'/performance-marketing/', '/performance-marketing', Record<never, never>, Record<never, never>>,
    '/privacy-policy/': RouteRecordInfo<'/privacy-policy/', '/privacy-policy', Record<never, never>, Record<never, never>>,
    '/services/': RouteRecordInfo<'/services/', '/services', Record<never, never>, Record<never, never>>,
    '/thank-you/': RouteRecordInfo<'/thank-you/', '/thank-you', Record<never, never>, Record<never, never>>,
    '/visual-identity/': RouteRecordInfo<'/visual-identity/', '/visual-identity', Record<never, never>, Record<never, never>>,
    '/website-design/': RouteRecordInfo<'/website-design/', '/website-design', Record<never, never>, Record<never, never>>,
    '/work/': RouteRecordInfo<'/work/', '/work', Record<never, never>, Record<never, never>>,
    '/work/[slug]': RouteRecordInfo<'/work/[slug]', '/work/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
  }
}
