{
  getObjects(
    bucket_slug: "comomaya-production", 
    read_key: "a59I38Pp6PQ3OIRd6QnAQNvatVHRuIAfN3dzAnv8bFMD7p0qAF",
    input: {
      query: {
        type: "portfolios",
        slug: "$bucket_slug"
      }
      props: "title,content,metadata"
    }
  ) {
    objects {
      title
      content
      metadata
    }
  }
}